# .symfony.insight.yaml
version: '1.0'
environment:
  env:
    DATABASE_URL: 'sqlite:///%kernel.project_dir%/var/data.db'

# SymfonyInsight ne prend pas en charge Docker, nous ne pouvons donc pas utiliser
# "docker compose up -d". De même, "symfony serve -d" n'est pas nécessaire car
# SymfonyInsight ne gère pas le serveur web.

# Préparation de l'environnement d'application.
pre_composer_script: "mkdir -p ${SYMFONY_INSIGHT_PROJECT_DIR}/var && chmod -R 777 ${SYMFONY_INSIGHT_PROJECT_DIR}/var"

# Exécutez composer install
# SymfonyInsight fait cela automatiquement, donc nous n'avons pas besoin de spécifier
# une commande "composer install" ici.

# Exécuter npm install et npm run build pour configurer les assets front-end.
post_composer_script: "npm install && npm run build"

# Exclure les répertoires non nécessaires pour l'analyse SymfonyInsight.
exclude:
  - 'docker'
  - 'node_modules'
  - 'var/data.db'